# Generated by Django 4.2 on 2024-04-22 13:28

from django.db import migrations, models
import django.db.models.deletion
import users.api.v1.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_code', models.CharField(help_text='Формат invite-кода: 6 символов, только цифры или латинские буквы (строчные или заглавные).', max_length=6, unique=True, validators=[users.api.v1.validators.validate_invite_code], verbose_name='invite-код')),
            ],
            options={
                'verbose_name': 'invite-код',
                'verbose_name_plural': 'invite-коды',
            },
        ),
        migrations.CreateModel(
            name='PhoneUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='Формат номера: 89991112233 либо +79991112233.', max_length=12, unique=True, validators=[users.api.v1.validators.validate_phone], verbose_name='номер телефона')),
                ('confirmation_code', models.CharField(blank=True, max_length=4, null=True, validators=[users.api.v1.validators.validate_confirmation_code], verbose_name='код подтверждения')),
                ('is_authenticated', models.BooleanField(default=False, verbose_name='аутентифицирован?')),
                ('activated_invite_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='code_activators', to='users.invitecode', verbose_name='активированный invite-код')),
                ('owned_invite_code', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='code_owner', to='users.invitecode', verbose_name='присвоенный invite-код')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи (по номерам телефонов)',
            },
        ),
        migrations.AddConstraint(
            model_name='phoneuser',
            constraint=models.CheckConstraint(check=models.Q(('owned_invite_code', models.F('activated_invite_code')), _negated=True), name='owned_invite_code_activation_constraint', violation_error_message='Пользователю нельзя активировать собственный invite-код.'),
        ),
    ]
